### ISSUE TITLE
Improve classic search result list layout

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#103]
Improve classic search result list layout for improved readability:

   * shorten labels and  header column names, eg Medium -> Media
   * add divider line under header row
   * left align all headers
   * add padding between artist & reviewed column
   * eliminate info icon vertical repeat
   * hard code to return 50 results
   * remove search type lable (it is evident from the form settings)
   * style via new searchTable css class
   * standardize search form layout

**Comment by RocketMan** [comment]
Patch landed, closing
