### ISSUE TITLE
PDF label printing

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#11]
As a keyer/librarian/md, I want to print zookeeper tags to my local laser printer, on standard label forms.

I would like to print to Avery 5161 or equivalent labels.

**Comment by RinTinCan** [comment]
merged to master, kzsu on 2018-06-14

**Comment by RocketMan** [comment]
Patch landed.  Closing.

**Comment by RocketMan** [comment]
Patch landed.  Closing.
