### ISSUE TITLE
Change album/label label on home page to match that used in other playlist displays

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#112]
Change album/label label on home page to match the playlist display. Currently the album & label fields are in separate columns on the home page, while the two are displayed as <ALBUM> / <LABEL> on the other playlist display views. Changing to the latter provides more efficient layout as well as consistency with the other views. Also make the following layout tweaks:

    * place "For complete album charting..." label at bottom of content div
    * use bold font for album rank value
    * remove top level table under the content div (not needed and complicates layout)

**Comment by RocketMan** [comment]
Patch landed, closing
