### ISSUE TITLE
Add ability move an NME to an arbitrary time point within a playlist

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#117]
Add ability move a spin to an arbitrary time point within a playlist. In order provide users the ability to set NME 'spin' times a function is required that will set the DB ID to a value that matches the time order in the playlist. Currently the tracks are ordered by ID (which served as a proxy for the playing order prior to the addition of the 'created' time field) and simply changing to sorting by created time will not work with older playlists. The moveTrackUpDown() method could be used to move the updated NME entry to the correct ID order but iterating over it to percolate the revised entry would not be efficient.

Suggested   Change:
Use the existing Playlist::moveTrackUpDown() function to update the id of the edited item so that its ID matches its new time position in the playlist. Note that there is a "TODO" hook in my push that could be used to wire in the new function.

**Comment by eric-gilbertson** [comment]
Another approach to the issue is to populate the created column for all spins in all playlists since this would allow all lists to be safely ordered by time instead of ID.  The older lists values could be populated starting with epoch and adding 1 second for each spin and the time values could be displayed only if greater than say this century.

**Comment by RocketMan** [comment]
Let's set aside backend implementation details for the moment.  I will be happy to take that on and provide you with the necessary APIs.

The larger question is how arbitrarily moving an entry affects timestamps.  Right now, the up/down mechanism swaps the timestamps.  That's fine for the use case where the DJ has entered a pair of entries out of sequence, but does not hold for arbitrary moves.

Consider a DJ who does a LID and then enters 5 spins.  He then realizes he forgot to enter a LID in zk, prior to those spins.  He enters the LID after the 5th spin, so it picks up 'now' as its time.  He then moves the LID before the 5 spins.  The only thing we know for certain is that the timestamp on the LID is wrong; however, we cannot infer anything about the timestamps on the 5 spins.

I suggest this general rule:
1. Erase the timestamp on any entry that is moved.  If the DJ wants to set one, he can do it post-move via #118;
2. The timestamps on all other entries in the playlist are unchanged.

**Comment by eric-gilbertson** [comment]
Actually I suggest that the prime use case that needs to be addressed is that posited in this ticket, eg the ability to 're-order' an NME whose time has been updated since this is the most direct method of addressing the use case you outlined, eg the ability to directly set the time of an NME that has been entered post-facto. The pending UI change allows a user to do this with a single edit rather than requiring DnD followed by a time edit.

**Comment by RocketMan** [comment]
Of course, I am developing the db code for #118, so we will support that.

My point is this:  It's fine that we are going to support repositioning via editing the timestamp, but it cannot be the only way.  We also need a visual way to reorder, such as a drag handle.

Also, we need to support reordering other entry types.  What value is there in limiting reordering to log entries only?  It caught me by surprise when I started looking at #118 that I could not change the timestamp on spins.  I'm sure DJs will be asking themselves the same question.

**Comment by eric-gilbertson** [comment]
Given spin time stamping has been operational for a while now without any requests from DJs to edit them, I'd say that there is not a great need for general time editing at this point. LIDs are an exception to this given that they must be broadcast & logged on the hour. Certainly the UI could be extended to support universal time  edits but it is seems to me that the first thing that needs to be done is to finalize how ordering will be handled in the DB, eg by continuing to order by ID or by changing to time ordering and adding a mechanism for spoofing time on older playlists. I would also note that adding support for reordering via DnD is orthogonal to this issue and that even with it the up/down arrows should probably remain because there is no widely accepted UI for conveying DnD functionality  to users.

**Comment by RocketMan** [comment]
Reordering support added on the PR branch.  Tracks are now automatically reordered based on the edit timestamp.

At minimum, you need to run:
`ALTER TABLE tracks ADD COLUMN seq smallint NOT NULL DEFAULT 0`

Everything should just work; you should not have to do anything more.  If you find something amiss, please let me know.

As the required functionality is now present, I am closing this slip.  Keeping #119 open to track the request for UI-based reordering for a future release.

**Comment by RocketMan** [comment]
For reference purposes, the change is as follows:

1. Natural sort order is still employed, unless explicit ordering is requested.  **This applies both to legacy playlists AND newly created playlists.**  In these cases, the `seq` column will be zero for all tracks in a playlist.
2. When (re)ordering is required, the new `seq` column is automatically called into action to record the sequential position.  **This column should be regarded as a private implementation artifact; its value should never be referenced nor relied upon outside the implementation class.**
3. To reorder a playlist entry, there are two possibilities:
    a. change the entry's timestamp and update via `IPlaylist::updateTrack/updateTrackEntry`, or
    b. call `IPlaylist::moveTrack`

In the case of `updateTrack`, the entry is reordered so that its timestamp falls in chronological sequence with other entries of the playlist.

In the case of `moveTrack`, the entry is reordered to appear in the position currently occupied by a reference track.  Both the entry and the reference track are specified by PK.
