### ISSUE TITLE
playlists by date is incomplete on beta for 1/10/2020

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#122]
compare the listings between production and beta for the following URL. note that one is complete and the other lists only 'Traditions'. 

https://zookeeper.stanford.edu:8443/?session=&action=viewDate&seq=selDate&viewdate=2020-01-10&month=1&year=2020

**Comment by RocketMan** [comment]
Hello Eric, as I said in an e-mail to you,

> I have deployed the time edit changes to stage.  **They are running against a snapshot copy of the production database**, so you can go wild without worry about upsetting anything in prod.
> 
> I did a snapshot of the prod database so I could see about how long it would take to run the conversion script... turns out about 10 minutes, so I will bear that in mind for scheduling the prod deployment.

**Comment by RocketMan** [comment]
Stage and prod are running against completely different databases.  There is no issue.

**Comment by eric-gilbertson** [comment]
Are you saying that these shows did not make it into the snapshot that is running on beta?

**Comment by RocketMan** [comment]
That is correct.  The snapshot was done Sunday or so.  Nothing in prod after that goes to stage.

The purpose of the snapshot was to test and time the conversion scripts.  There is no automatic synchronization of the two databases.
