### ISSUE TITLE
Revisit session cookie scope

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#129]
Zookeeper's session cookies are temporal (meaning non-persistent, memory only).  These cookies are automatically deleted by the browser when the window closes, or by zookeeper upon explicit logout.

Historically, the session cookies have been considered 'optional', as the session ID is explicitly provided as part of the query string or in a FORM POST.  The session cookie was a nicety to maintain session state in the event the user navigated away from the site and then returned, but the cookie was not essential for functioning of the site.

Theoretically, session cookies should be available across multiple tabs/windows of a given browser.  It seems sometimes, it is possible to get a window open somehow that does not contain the temporal cookies.

We may want to consider making the cookies persistent (normal cookies).  Provided the cookies are marked http-only and secure, this should present minimal issues, and will ensure the cookies are not 'lost' by reliance on browser-specific behaviour around temporal cookies.

**Comment by eric-gilbertson** [comment]
It would be very nice to not have to include a session ID in hrefs and POST operations. Doing so clutters the code and makes bookmarks session specific. It seems that there should be a straightforward solution to the production vs staging cookie mixup issue, as many other deployments must also have hit this problem. Some possible solutions include using seperate server instances for the two versions and/or namespacing the cookies with the server hostname.

**Comment by RocketMan** [comment]
session management changes landed 2.10.2.  since this release, sessions have been maintained only in cookies (session ids are no longer passed in the URL or form data), and the cookies are scoped to the specific zookeeper instance to avoid collision.
