### ISSUE TITLE
Increase default display length of the DJ reviews view from 15 to 50

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#147]
Increase default display length of the DJ reviews view from 15 to 50. The reviews page at:

http://localhost:8080/?s=byReviewer&n=1631&p=0&q=50&action=viewDJReviews...

is invoked with a default page length, eg "q" of 15 which makes it difficult to quickly search a DJ's reviews. Increasing this value to 50 would greatly simplify this process.

**Comment by RocketMan** [comment]
Thanks Eric.  Patch landed hotfix-2-8-0, master; closing
