### ISSUE TITLE
Recent reviews page is empty when using MySQL 5.7

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#155]
Recent reviews page is empty when using MySQL 5.7. Due to a change in the default validation the  query that is used to populate this page, eg Review::getRecentReviews() always returns an empty set and the following warning:

Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.table.col' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

The issue can be worked around by executing the following query (as root):
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

**Comment by eric-gilbertson** [comment]
Jim, would modify the 'getRecentReviews() SQL query so that it works with the current version of MySQL?

**Comment by RocketMan** [comment]
Of course, but this is not the only query affected, it's just the one you ran into.  There is not much point fixing this one with others still broken, so plan is to fix them all.

For now, for zookeeper to work correctly under MySQL 5.7, you have to disable ONLY_FULL_GROUP_BY.

**Comment by eric-gilbertson** [comment]
There may indeed be other queries that are impacted by this change but the Recent Reviews query by far is the one developers are most likely to encounter. As such it would be beneficial to get it fixed and merged into master without having to wait for other cases to be identified and fixed.

**Comment by RocketMan** [comment]
Not 'may indeed be', there are other queries affected.  I have already identified what needs fixing and will apply the fixes within the next couple days.
