### ISSUE TITLE
Set Zookeeper background color to "Stanford red"

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#163]
Set Zookeeper background color to "Stanford red". A Git change has been submitted to change the background color of the station web site pages to the standard Stanford red, eg #8C1515 so that it matches the color in other university web pages. Once this change has been accepted the background color of the KZSU version of zookeeper should be changed to the same value (as well as the KZSU logo).

**Comment by RocketMan** [comment]
Are you planning to submit a PR for this?

**Comment by eric-gilbertson** [comment]
Yes, I've made the changes. Just waiting to confirm that no one complains about the color change before submitting it to ZK.

**Comment by RocketMan** [comment]
Thanks Eric.

Patch landed hotfix-2-9-0 and deployed to prod; closing.
