### ISSUE TITLE
Add CD reviewer name to the 'adds' list 

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#17]
Add the CD reviewer name to the 'adds' list in order to help DJs identify disks that they might be interested in investigating. Adding the reviewer would provide insight as to the disk music type. This is in part driven by the fact that the general library is so broad and because there is no way to identify sub-genres. Knowing the reviewer is a good surrogate for this and as such would help DJs quickly determine which adds they should investigate.

**Comment by RocketMan** [comment]
Patch landed, closing
