### ISSUE TITLE
Add options to select DJ and genre types to recent reviews page

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#184]
Add options to select DJ and genre filter types to "recent reviews" page. This change will allow users to quickly find new reviews from certain categories, eg blues and country and by a particular reviewer as well as the ability to filter out genres that are not of interest. Changes include:

   * add DJ selection element to page header, default value is "All"
   * add genre selection radio button group with default of all
   * store user configuration in local storage upon configuration changes
   * restore user's last configuration upon page load
   * remove "Your most recent reviews" block from page

**Comment by eric-gilbertson** [comment]
What is the purpose of the RSS button located at the top/right of the current implementation? Clicking it displays a new page that appears to be an XML representation of the page.  If it is no longer used I would like to remove it.

**Comment by RocketMan** [comment]
> What is the purpose of the RSS button located at the top/right of the current implementation? Clicking it displays a new page that appears to be an XML representation of the page. If it is no longer used I would like to remove it.

https://en.wikipedia.org/wiki/RSS

**Comment by eric-gilbertson** [comment]
Yes, I am familiar with RSS. The question is whether providing this button on the Recent Reviews page serves any purpose and whether anyone is using it?

**Comment by RocketMan** [comment]
If you want to remove it, you will need to find some way of indicating RSS feed availability on the page, and then apply that across all three pages with RSS feeds (charts and adds being the other two with feeds).

For example, I would have no objection to using a more modern feed icon like this ![](https://www.mozilla.org/media/img/trademarks/feed-icon-14x14.2168a573d0d4.png).  The feed can be inferred from the context, so you can omit the existing text label and use just the icon.
