### ISSUE TITLE
Make playlist artist name search case insensitive

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#185]
Make playlist artist name search case insensitive when entering names into the artist name element. Currently this compare is case sensitive which caused my search for McKnight to fail because it had been entered into the system as Mcknight. Can't think of any down sides to loosening the search operation.

**Comment by RocketMan** [comment]
This is in the playlist editor?  It should already be case insensitive.  For example, here is my entering the artist name with random case:

![Screenshot from 2020-09-12 14-51-44](https://user-images.githubusercontent.com/6860356/92997024-e728ac00-f507-11ea-8a75-743498c80588.png)

**Comment by eric-gilbertson** [comment]
It turns out that what I encountered was not a case issue but something to do with how the list is refreshed after the user manually tweaks the artist name. Not sure it needs to be changed but here is what I encountered:

  * paste in an artist name, eg Mcknight, Val
  * change k -> K
  * tab out - expect pick list with 'Stroke to be displayed but nothing is shown

I'll leave it to you to decide whether the behavior should be changed or not.

**Comment by RocketMan** [comment]
Thanks Eric.  One problem is that it was running the search only on keyup.  I've updated it to work for paste as well.

Please check it out in production at your convenience.

**Comment by eric-gilbertson** [comment]
Thanks, the current behavior looks good to me.
