### ISSUE TITLE
Change edit playlist tracks entry from POST to GET so that DJs can back into the page

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#192]
Change edit playlist tracks entry from POST to GET so that DJs can 'back' into the page. Currently the page is entered with POST and thus if a DJ clicks on a link in the editor it is not possible to return to it using the browser's back function. Changing the page entry point to GET will fix this issue.

**Comment by RocketMan** [comment]
Hello Eric, can you please give the exact steps to reproduce this?  For me, I can back into all pages related to Edit Playlist, in both firefox and webkit.

**Comment by eric-gilbertson** [comment]
Hey Jim, looks like you are correct. I cannot reproduce this. Closing, will reopen if I come across it again.
