### ISSUE TITLE
Spin time is lost when editing playlist start time

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#193]
Spin time is lost when editing playlist start time. Use case is a DJ re-running a past show that airs at different time than the original. Using playlist export/import a new playlist for the repeat broadcast can be created but the spin times are lost if the DJ changes the show start time. Preferred behavior is to have the spin times adjusted to reflect the new show's start time.

**Comment by RocketMan** [comment]
Thanks Eric.  Not to put too fine a point on it, but changing the start time does not automatically erase the timestamps, only changing the start time in such a way that the timestamps no longer fall within the show's new time range.  For example, if the start time were 9am and you changed it to 8am, no timestamps would be affected.  The logic is here: https://github.com/RocketMan/zookeeper/blob/23bfd11aa6800d702a5cc2ff06c8b04545eb5e53/engine/impl/Playlist.php#L201-L226

But I see what you're saying... just like date changes, where we automatically adjust the timestamps, if the DJ changes the show **time** to a new window, then we should similarly adjust the timestamps.  It's a feature enhancement more than a bug, but I think it's a worthwhile one, especially the way shows are being created these days.

**Comment by RocketMan** [comment]
In addition to the changes that we're making here, I think it would be useful to add Duplicate Playlist to the merged New/Edit Playlists functionality #84 when we do that.  In this way, we address the use case of a repeat broadcast without forcing the DJ to go through multiple steps of export/import and edit.

**Comment by eric-gilbertson** [comment]
I agree that a duplicate playlist button is another worthwhile improvement. Suggest first adding the time correction part though so that it can be deployed quickly (I'm currently busy with a Python 3 upgrade to the station web app). We have a number of rerun shows these days with no playlists and I'd like to send out a reminder about this feature but doing so without first addressing the time shift issue will create confusion.

**Comment by RocketMan** [comment]
I have a candidate in stage.  Please have a look and let me know.

Note that you must change both the playlist start and end times to trigger the spin time change, which would normally happen if you're airing a show at a different time.  This is to avoid someone's simply changing the start time only and then getting all the spin times changed unexpectedly.

**Comment by RocketMan** [comment]
Everything looks good to me.  I'm planning to release over the weekend.  If you see anything amiss on stage, please let me know.

**Comment by RocketMan** [comment]
I also added a Duplicate button on the Edit Playlist screen.  Combined with the spin time rebase fix, this should cover the use case pretty well.

**Comment by eric-gilbertson** [comment]
Just tested it - works great.
