### ISSUE TITLE
Add push notification for spins

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#195]
Add push notification for spins. Currently clients must poll ZK in order to obtain the current track (if any). Converting to push notification would simplify the code needed to post the current track to RDS notification systems and eliminate the latency inherent in polling. The feature should support the following:

   * notification to user configurable URL, eg kzsu.stanford.edu/logsong?showname=...&djname=...artist=....&track=....&album=...
   * notification for real time track entry, e.g. in studio mode
   * notification for  pre-built track 'entry', e.g. Covid mode
   *  send an empty song notification when a playlist end time is reached

Issues to consider include the following:
   * GET or POST for the notification request
   * do the notifications need to be authenticated
   * fix or user definable format for the notification message

**Comment by eric-gilbertson** [comment]
Thinking about this a bit more it seems that sending an empty track upon show end is an important feature since it tells the receiver when a show has finished. Moving this item to the should have group.

**Comment by RocketMan** [comment]
Landed 2.10.7, deployed to prod.
