### ISSUE TITLE
Possible minor bug when an error is encountered on the "Create Playlist" screen.

### ISSUE THREAD

**Issue by RobertWise** [RocketMan/zookeeper#203]
This may be a relatively unusual use case, but I thought I would mention is.

For the Wednesday Night Live program I (Smurph) have been uploading old recordings for rebroadcast.  As of last week, I have started adding Zookeeper playlists for these rebroadcasts.  I have been doing the show upload and playlist creation on Tuesday mornings, one day ahead of the shows broadcast on Wednesday evening.

On the "Create Playlist" screen ( https://zookeeper.stanford.edu/?action=newList ) I would like the Air Name for the show to show the hosts air name (Gus The Fat and the Peanut Gallery) rather than my air name.  When I tried this initially, I encountered an error message saying that the air name I had chosen already existed.  I assume that is because that air name is associated with Will's Zookeeper account, which makes logical sense.

I was easily able to work around that issue by using a variation of their DJ Name which I believe will work fine.  Today, however, I noticed that when I received the error message about the air name being already in use, the "Show Date:" field which I had initially set to tomorrows date via the datepicker had been reset to today's date.  I thought that this date reset upon error message receipt might be a bug so I am reporting it here.

Thank you as always for all of the work coding and maintaining Zookeeper.

**Comment by RocketMan** [comment]
Hello Smurph, hope you are well.  I can confirm, the resetting of the date during playlist creation is a bug.  Thank you for reporting it!

And indeed, airnames are linked to specific DJs and cannot be reused.  Administrators (MD, PD) can move airnames between DJs, but in any given moment, each airname is associated with only one DJ.

You are a php coder, are you not?!?  I welcome you to jump in!  See [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) for a tour of the code.  There are several interesting epics that you could take on, if interested; e.g., #7, #2.
