### ISSUE TITLE
Truncate duplicated playlist tracks that fall after show end time

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#235]
Truncate duplicated playlist tracks that fall after show end time. Currently all tracks of say a 3 hour show  are copied to a duplicated playlist even if the latter is only 1 hour. As an example see the Magnetized Toner playlist for 6/24/2021.

Suggest Change:
Truncate tracks in the new playlist the fall after the end time of the new show.

**Comment by RocketMan** [comment]
Good one!

Fix landed hotfix-2-10-10, deployed to prod.  Closing.
