### ISSUE TITLE
CSS regression testing...

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#24]
... in support of #22.

The changes have been deployed to stage, https://zookeeper.stanford.edu:8443  Please compare to production, https://zookeeper.stanford.edu  There should be no visible differences between the sites.

We want to hit as many platforms/browsers as possible.  Please leave your findings, including success, here.

**Comment by RocketMan** [comment]
Firefox 60.6.3esr (Solaris) - OK
GNOME Web 3.30.3/WebKitGTK 2.24.1 (Solaris) - OK
GNOME Web 3.22.7/WebKitGTK 2.18.6 (Debian) - OK

**Comment by joncousins** [comment]
Just had a super quick look, Jim, and everything seemed as I'd expect – with one minor anomaly.

I logged in to Zookeeper, went to the A-file page, then to Adds. Clicked on the Label header, to view in a-z order, but the Uncle Meg (artist) album appears at the top of the list, with a label Hog Hob Musik, which ought to be further down the list.

Don't know, could be an error in how it was keyed (is there a leading space, for example?) but wanted to log.

Cheers, and thanks, Jon

**Comment by RocketMan** [comment]
Thanks Jon!  Hog Mob Music does indeed have a space at the beginning.  I am going to open a bug against the Library Editor to trim leading and trailing whitespace.

**Comment by joncousins** [comment]
^ Cheers Jim, thanks for being responsive! There's also another current issue live in Zookeeper, and also therefore manifesting itself in this staging version.

The Click To Listen Live button, top right hand corner, points to listenlive.stanford.edu which appears to no longer exist (perhaps it disappeared in a recent rejig of subdomains?)

I did report this to the Computing list a fair time ago but as it didn't get picked up by anyone, perhaps it could be fixed in this round of improvements, please?

Looks like the "correct" URL is kzsu.stanford.edu/live – this is, at least, one that works. Thank you!

**Comment by RocketMan** [comment]
No worries, Jon.  Thanks for letting me know about the broken link; I have opened a new slip for it and will fix it for the 2.2.0 deployment in support of #6.  I expect that to go live later this week or next.

At any time, please feel free to open issues for bugs you encounter or enhancement ideas under the 'Issues' tab of the repo.  Thanks again Jon!

**Comment by romain2k** [comment]
I noticed an anomaly when comparing my most recent playlist on the stage site vs. production.

Third from the bottom, the album on production is: 
Ravel: Orchestra Works, Vol. 3

Stage has: 
Vol. Ravel: Orchestra Works 3/Naxos

production:
https://zookeeper.stanford.edu/?action=viewDate&seq=selList&playlist=38877

stage:
https://zookeeper.stanford.edu:8443/?action=viewDate&seq=selList&playlist=38877

Also in the album field, is there a clearer way to set the label apart from the title?

Thanks,
Romain

**Comment by RocketMan** [comment]
Thanks Romain!  As it turns out, the css changes (2.1.0) went live on Tuesday and stage became the forthcoming timestamp feature from Eric (2.2.0-DEV).  I've opened a separate slip to track the issue.

**Comment by RocketMan** [comment]
Patch landed, closing
