### ISSUE TITLE
Clear auto-filled album info when artist field is modified

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#264]
Clear auto-filled album info when artist field is modified. This is needed to handle case where an artist & album is select during PL track entry in manual mode but the desired track is not present. In this case the user has to empty out the artist field in order to clear the album and label fields. 

Suggested Change:
Clear all auto-filled fields when the artist field is modified

Reproduce: (from PL track entry page in manual mode)
   * enter artist, e.g. Ray Davies
   * select album, e.g. Lola
   * remove 's' from Davies - auto-filled fields should clear

**Comment by RocketMan** [comment]
Thanks for this.

I have deployed as a hotfix to prod.  Please check it out.  If it looks good over the weekend, I'll merge to the new release.
