### ISSUE TITLE
User sorting in admin screen does not match the user name display order

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#281]
User sorting in admin screen does not match the user name display order. The sorter sorts by last name but the display is <FIRST> <LAST>. Suggest swapping one or the other so that the sort and the display match.

**Comment by RocketMan** [comment]
Hello Eric, can you please explain further what you see happening, and what is expected?  Thanks.

**Comment by eric-gilbertson** [comment]
Adding screenshot showing the issue. Note that user names are sorted in decreasing order of the user's last name but the names are displayed as <FIRST> <LAST>.  Suggest changing either the display to show as <LAST> <FIRST> or the sorting to order by first name so that the display matches the sort order.

![admin_sorting_issue](https://user-images.githubusercontent.com/1987922/164576347-6ced9d00-a2bb-4da0-8678-3c5c03103045.png)
.
