### ISSUE TITLE
Add ability to identify duplicate playlists from the REST API

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#293]
Add ability to identify duplicated playlists so that playlist consumers can tell whether it represents a new or rebroadcasted show. This can currently be done by examining the list title but this is fragile.  

Suggested Enhancement:
Add a 'duplicate' flag to the lists table and set it if the list was created by duplication and include it in the output of the playlist query REST API.

**Comment by RocketMan** [comment]
PR landed, closing
