### ISSUE TITLE
Add ability to enter tag id into Artist field of the playlist editor.

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#296]
Add ability to enter tag id into Artist field of the playlist editor. Allowing entry of tag ids into the artist field would eliminate the need for DJs to switch between Manual and Tag ID modes when entering the different track types thereby simplifying entry for the common case of playing both station and personal disks.

Suggested Change:
Change label of the "Artist" input to "Artist/ID". Upon entry of a 6 digit tag id into the Artist/ID field, display the disk associated with the tag id in the album picker dropdown. Upon selection of the disk populate the remaining fields in the same manner as when the user enters an artist name and selects a disk. (see attachment)

![tag_entry](https://user-images.githubusercontent.com/1987922/164578634-58cc62dc-3e11-4399-bdbc-fc1e2a16472d.png)
.

**Comment by RocketMan** [comment]
I like this a lot.  Thanks for the suggesion!
