### ISSUE TITLE
PR #25 Playlist formatting issue

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#30]
I noticed an anomaly when comparing my most recent playlist on the stage site vs. production.

Third from the bottom, the album on production is: 
Ravel: Orchestra Works, Vol. 3

Stage has: 
Vol. Ravel: Orchestra Works 3/Naxos

production:
https://zookeeper.stanford.edu/?action=viewDate&seq=selList&playlist=38877

stage:
https://zookeeper.stanford.edu:8443/?action=viewDate&seq=selList&playlist=38877

Also in the album field, is there a clearer way to set the label apart from the title?

Thanks,
Romain

P.S. I see this in Chrome and Safari on MacOS 10.13 and 10.14.

_Originally posted by @romain2k in https://github.com/RocketMan/zookeeper/issues/24#issuecomment-495012072_

**Comment by eric-gilbertson** [comment]
this is a side effect of the name swapping used to show names as 'first last' and not 'last, first'. question is how to handle this. the swap could be removed but then common names would again backwards. thus i suggest limiting the name swap only to names that contain no other punctuation characters. even with this change there might be a few other edge cases but i feel that it is worth the overall readability improvement that this feature provides.

**Comment by romain2k** [comment]
Seems odd to me that name swapping is getting applied to the album title. Why not just the artist name? 

That also seems like an opportunity to badly scramble the artist name if it's a group with a comma in the name.

**Comment by eric-gilbertson** [comment]
Agree that it is best not to swap the artist title. Still think though that it is best to keep the swap for the artist name since the overall readability benefits outweigh the possibility of an occasional mis-swap. 

As to clarity between album name and label, the former is red on my branch which distinguishes it from the label portion which is black. I don't know why it is different in staging.

Have also fixed the time issue when songs are moved up and down, eg the spin times get swapped as well.

**Comment by RocketMan** [comment]
The album is red only if it is a hyperlink; the black ones are DJ-supplied albums.

About the timestamp, per my [earlier comments](https://github.com/RocketMan/zookeeper/pull/25#issuecomment-493931959), it could go a couple ways -- the way you had it (the times don't move) or clearing the time on the spin (as we cannot reasonably guess the time, if the user is moving things around).  There may be other possibilities.  However, swapping the times would put the spins out of temporal sequence, which could be confusing.

**Comment by eric-gilbertson** [comment]
pushed up a few more tweaks to the time stamping.  main change was to support romain's use case, eg no time stamp when importing a playlist but to add one on first update of an entry following the import, eg do an edit/save operation when the imported item is played and it will get stamped.

as to moving tracks up & down, i agree that this is the best approach and that behavior has been restored in this commit ( 81143be..18e3634)

**Comment by romain2k** [comment]
Thanks, Eric!

**Comment by RocketMan** [comment]
Thanks Eric.  Patch landed and deployed to stage.

**Comment by eric-gilbertson** [comment]
pushed another small change that prevents time stamping when updating an old playlist. i think it is ready for prime time now.

**Comment by RocketMan** [comment]
Hello Eric, I'm not seeing a PR and can't find the change... can you please open a PR and I'll merge.

**Comment by eric-gilbertson** [comment]
done.

**Comment by RocketMan** [comment]
Thanks, patch landed and deployed to stage.

There was a merge conflict around updateTrack that I resolved manually.  Please check to ensure everything looks as expected.

**Comment by eric-gilbertson** [comment]
will do. btw, do you know why i often get  merge issues pushing up to my own branch? it often flags a merge conflict against the changes in my previous commit. never experienced anything like this before with git.

**Comment by RocketMan** [comment]
> do you know why i often get merge issues pushing up to my own branch?

I don't think it is anything you are doing... I have run into similar situations.  My sense is that the github platform has bugs.

I'm happy with where this is right now.  Do you want to announce that the feature in stage for review, before we promote it to prod?

**Comment by eric-gilbertson** [comment]
yes, i will send something out this evening.

**Comment by RocketMan** [comment]
Patch landed, closing.
