### ISSUE TITLE
Add seconds field to the spin time entry input elements

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#308]
Add seconds field to the spin time entry elements. Currently the spin time accepts only hours & minutes. Adding seconds to these inputs allows more precise control of the track play messages. Since the backend already takes a full timestamp, changes are required only in the frontend, e.g. show seconds on the two spin time input fields and carry these values through to the update logic. Note that seconds will not be displayed in the playlist views because it clutters the display and because they are not important in view mode.

**Test Cases:**
- add new spin entry and check that seconds are stored in the DB
- edit existing spin entry & confirm in DB
- view playlist and confirm seconds are not displayed
- confirm seconds handled properly in playlist duplication
- confirm seconds handled properly in import & export of playlists

**Comment by RocketMan** [comment]
Closed by #309
