### ISSUE TITLE
zk.stanford.edu

### ISSUE THREAD

**Issue by mapninja** [RocketMan/zookeeper#31]
zk.stanford.edu used to point to zookeeper, but doesn't seem to work, now.

**Comment by RocketMan** [comment]
@MarkCLawrence it looks like the alias `zk.stanford.edu` has disappeared.  Can we please bring that back?

This is a request only for the NetDB DNS alias.  There is no impact to the SSL certificate, as the server is setup to do a redirect from zk to zookeeper.

Thanks Mark.  Cheers.

**Comment by MarkCLawrence** [comment]
I probably won’t be able to do that until 8th June when I get back from vacation as I don’t have my computer with me. Don’t think I can login to netdb from my phone.
Will check with my companions to see if any have Stanford VPN set up

Sent from my iPhone

On May 23, 2019, at 20:30, Jim Mason <notifications@github.com<mailto:notifications@github.com>> wrote:


@MarkCLawrence<https://github.com/MarkCLawrence> it looks like the alias zk.stanford.edu<http://zk.stanford.edu> has disappeared. Can we please bring that back?

This is a request only for the NetDB DNS alias. There is no impact to the SSL certificate, as the server is setup to do a redirect from zk to zookeeper.

Thanks Mark. Cheers.

**Comment by RocketMan** [comment]
Enjoy your holiday, Mark.  Don't worry about this right now, there is no urgency.  It will still be here when you get back...

Cheers

**Comment by MarkCLawrence** [comment]
Fixed.
I was able to login to Netdb from my iPhone.


Sent from my iPhone

On May 27, 2019, at 12:35, Jim Mason <notifications@github.com<mailto:notifications@github.com>> wrote:


Enjoy your holiday, Mark. Don't worry about this right now, there is no urgency. It will still be here when you get back...

Cheers

**Comment by RocketMan** [comment]
Thanks Mark.  Issue resolved, closing.  Stace, thanks for bringing this to our attention.

Mark, enjoy the rest of your holiday!
