### ISSUE TITLE
Add 'event type' field to track spin notification event structure

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#326]
Add 'event type' field to track spin notification event structure so that the different event types can be easily identified. Currently special events, e.g. no playlist, are identified by setting fields with special values. Adding an event_type field that explicitly identifies the each event would eliminate the need for data inspection to determine the type and document the available event types, e.g. PLAYLIST_END and TRACK_START for consumers of the service.

**Comment by RocketMan** [comment]
This is now in production.  Leaving this open until it lands in master.

There are two new properties in the notification:
* type: zookeeper
* event: [ none | show | track ]

'show' means a show is on-air but no track is available; 'track' means there is a show with a track now airing, and 'none' means no show is available.
