### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#34]
Hello Eric,

I notice in your most recent changes that you're using the form **'self::*method*'** rather than **'$this->*method*'** to access instance methods.  **self::** should be used only to access static properties and methods but not instance methods, as it suppresses polymorphic behaviour.

You will notice elsewhere in the application, self:: is used only when accessing a static property or method; otherwise, $this-> is used.

Can you please review your code; if a method is not static, then all invocations of that method from within the class should be of the form $this->method(...)

Thanks Eric!  Cheers.

**Comment by eric-gilbertson** [comment]
change pushed & PR pulled.
