### ISSUE TITLE
Differentiate Zootopia from scheduled shows on Schedule page

### ISSUE THREAD

**Issue by nathankim7** [RocketMan/zookeeper#345]
Can we add some sort of visual differentiator for Zootopia on the scheduled page (different colour/pattern/etc.)? It is a music show, but having it be indistinguishable from the other music makes it harder to spot issues on the schedule page. For example, I just discovered that Mix Tape has only 1 hour scheduled for whatever reason when it should be 2 hours long.

**Comment by RocketMan** [comment]
Hello @nathankim7,

Thanks for the suggestion.  The schedule page is part of the station website; it is not part of zookeeper.   FYI, zookeeper is the music and playlist database at https://zookeeper.stanford.edu/.

You will need to contact @eric-gilbertson or @bufordsharkley for requests to change the schedule page.
