### ISSUE TITLE
Zookeeper playlist overlaps DJ entered playlist

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#353]
Zookeeper playlist overlaps DJ entered playlist. See playlists for 10/16/2022 for an example. In this case a live DJ created a playlist for 3-4 a.m. while Zookeeper was in the process of creating a 2-6 a.m. playlist resulting in two playlists for the overlapped time.

Suggested Change:
Stop creation of Zookeeper playlist when another playlist is created for the current time.

**Comment by RocketMan** [comment]
Patch landed in production, closing
