### ISSUE TITLE
Cannot add more than two playlists for a given day

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#374]
Cannot add more than two playlists for a given day. When a third list is added one of the two previously entered lists disappears. Happens consistently and probably started around one week ago. Most recent occurrence was around 8:30pm (PDT) on 12/26/2022. 

Reproduce:
  * add playlist for 6-7am & confirm in playlists by date page  
  * add playlist for 7-8am & confirm two entries in playlists by date page
  * add playlist for 8-9am - only the two most recently entered PLs are shown in the view page

**Comment by RocketMan** [comment]
Thanks for that.

I suspect one of the lists had no entries.  Zk has a 'feature' where it permanently deletes an empty playlist on the same date as a new one, irrespective of show time.

I suppose we could just drop this feature all together, as it was introduced before My Playlists to avoid duplicates, where certain DJs had a habit of doing New Playlists multiple times for a given list.  Alternatively, we could change it to delete only empty lists on the same date that have exactly the same start and end times.  Do you have a preference?

**Comment by eric-gilbertson** [comment]
Seems that modifying the process to delete an empty playlist when a new one of the same time might be a good compromise that would prune redundant lists while allowing a case where a DJ might enter two empty lists at different times. The latter case might occur when a non-music show airs multiple times in one day, e.g. a news show.

**Comment by RocketMan** [comment]
Thanks, the fix is now in prod.  It should no longer be necessary to enter a track to prevent auto-deletion.
