### ISSUE TITLE
No hits when entering R.E.M. into the playlist artist field

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#379]
No hits when entering 'R.E.M.' into the playlist artist field. Double checked that this is how the REM disks were actually entered into the library.

Expected Result:
List of the 20 (or so) REM disks in the Zookeeper library.

**Comment by RocketMan** [comment]
In addition to the code fix, made the following ops changes:
1. removed the full text stopword list (as already indicated in our INSTALLATION instructions);
2. dropped the minimum full text word length constraint;
3. restarted mysqld, and
4. regenerated the full text indices on `albumvol`.

Fix deployed to prod and ops changes complete, closing
