### ISSUE TITLE
Add 'import tracks and URLs' option  to the library editor's track edit page

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#384]
Add a find tracks and URLs button to the library editor's track edit page. Currently this information must be manually entered. Adding an option to automatically populate the name and URL fields would simplify the disk entry process and eliminate typing errors. The track names could be obtained from a service like discogs and the URLs can be obtained via the YouTube api.

**Comment by RocketMan** [comment]
Changes landed in prod; closing
