### ISSUE TITLE
Link to classic search

### ISSUE THREAD

**Issue by fecundf** [RocketMan/zookeeper#402]
I added a bookmark to https://zookeeper.stanford.edu/?action=search so I can get to classic search- useful for partial word searching and limiting searches to specific fields- it is a different kind of search,

My vote is to keep classic search functional, and findable. Maybe as a link from the new-search results? I don't know where it should go, just that I can't find it now.

**Comment by RocketMan** [comment]
I have integrated classic search into the top navigation search function.  There is a new filter at the right side of the search field.  The default 'All' gives the usual full-text results, whilst the other options provide the classic search functions.

The results you get in this way will be exactly the same as they had been with the now deprecated classic search form.


![Screenshot from 2023-05-23 18-56-47](https://github.com/RocketMan/zookeeper/assets/6860356/0ebf72f9-bac6-465e-a0fc-a95bf7adbac6)
![Screenshot from 2023-05-23 18-57-43](https://github.com/RocketMan/zookeeper/assets/6860356/1e5fe314-df2d-4048-b4ee-3e13eaacf721)
![Screenshot from 2023-05-23 18-58-05](https://github.com/RocketMan/zookeeper/assets/6860356/9905f8fa-6ac6-4ae2-8988-4fc837f8ac1e)

**Comment by eric-gilbertson** [comment]
Nice to see that the classic search function is back. I used it fairly often. Suggest also adding a 'Playlist' option to the search selection dropdown and have it do a full-text search against playlists. The use case is to quickly find something played in the past that isn't in the station library.
