### ISSUE TITLE
Easier to find link to a playlist

### ISSUE THREAD

**Issue by fecundf** [RocketMan/zookeeper#403]
Low priority request here. If I want to link to a particular playlist - and I remember there is a way but I can't remember what it is-

First I go to Playlists by DJ & see a list of all my playlists. They aren't links though so I can't right-click & "Copy Link..."

Then I click into a playlist but I can't share the URL because it is `https://zookeeper.stanford.edu/?`

So my 1st suggestion is to have the URL from that playlist-picker be a full URL to that playlist.

2nd is to have a "Share Playlist"  link on any playlist page though I'm not sure what it should do!

Playlist "By Date" does have links to playlists that are copy/paste friendly. And I know there is a link somewhere already to get the printable playlist.

**Comment by RocketMan** [comment]
FYI, it is currently on the dot menu inside My Playlists.  Go to My Playlists, then Open a playlist.  In the upper right corner, there is a dot menu.  This menu includes link to playlist  and the export options.  Selecting Link to Playlists copies the public URL to the clipboard.

![Screenshot from 2023-06-03 15-28-56](https://github.com/RocketMan/zookeeper/assets/6860356/6720f68b-cd60-478f-857e-30c7b6178d56)

The idea of putting it here (in the playlist editor) is that a DJ might want to share it whilst the show is on-air.  In this case, he already has the playlist open.  That said, I like your suggestion for Share Playlist from any playlist as well, and will look to add that soon.
