### ISSUE TITLE
Your track was not saved: parsererror

### ISSUE THREAD

**Issue by fecundf** [RocketMan/zookeeper#429]
I'm editing https://zookeeper.stanford.edu/?subaction=viewListById&playlist=48607 and seeing `Your track was not saved: parsererror` - using Firefox on Windows.

I started by pasting in `Dukes Of Stratosphear` to the Artist field, chose the album `25 O'clock`, then picked track 3 from the menu `What In The World??...` next I typed in the min & sec (`03` was pre-filled) `05:48` clicking "Add Item" gives this error.
![image](https://github.com/RocketMan/zookeeper/assets/317592/d7374c45-2504-466b-9252-fc4f4c551389)

Interesting, I was able to save track by editing the track name to `What In The World?`

**Comment by fecundf** [comment]
Yikes the playlist now looks like this- I'm going to delete the bogus tracks

03:05 pm	| The Dukes Of Stratosphear | What In The World? ...
03:05 pm	| The Dukes Of Stratosphear | What In The WorldjQuery36406110974977345341_1704724551332...
03:05 pm	| The Dukes Of Stratosphear | What In The WorldjQuery36406110974977345341_1704724551332...
03:05 pm	| The Dukes Of Stratosphear | What In The WorldjQuery36406110974977345341_1704724551332...

[image](https://github.com/RocketMan/zookeeper/assets/317592/ba7a3bd0-935c-40c1-8378-2bd5b2674b74)

**Comment by RocketMan** [comment]
Thanks for the prompt bug report!

I am able to reproduce.  t seems related to the trackname, What in the World??...    Am investigating now.

**Comment by RocketMan** [comment]
The problem has been fixed.  You may need to reload or exit and re-enter the playlist editor.

Thanks again for reporting!
