### ISSUE TITLE
A-File default sort sequence

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#43]
There has been a change in the default sort sequence:

* In production, the Current File sorts by artist, and the Adds by A-file number.
* In stage, both Current File and Adds sort by A-file number.

Just want to confirm this is expected/intended.

**Comment by RocketMan** [comment]
In the new code, it seems the default sort sequence of Current File is different, depending on whether you're logged in or not.  The observation above -- that it is ordered by A-file number -- is true when logged out.  When logged in, the default sort sequence is different; I cannot make out what it is sorting by in that case.  Does not seem to be any of reviewer, A-file number, or artist.

**Comment by eric-gilbertson** [comment]
Agree that it should be consistent. Will restore to sorting by order and set it visually.

**Comment by RocketMan** [comment]
Patch landed, closing

**Comment by RocketMan** [comment]
Reopening.

In the latest code, I am seeing the new default sequences as proposed, but only if *not* logged in.  When I am logged in, it seems the same as before: no visual indication of the sort column, and unknown sort sequence on the Current File.

Note, I am logged in with 'n' (Add Manager) privileges.  Not sure if this is true for general users also, or only for 'n' users.

**Comment by eric-gilbertson** [comment]
issue is specific to the 'n' privilege which causes edit icons to be placed in the left column which is the default sort column. suggest fix: relocate the edit icons to the rightmost column.

**Comment by eric-gilbertson** [comment]
Fix: always set sort to Cat column even when use with 'n' access is logged in.

**Comment by RocketMan** [comment]
patch landed, closing
