### ISSUE TITLE
Library editor creation: allow non-matching media type for Discogs pull?

### ISSUE THREAD

**Issue by bufordsharkley** [RocketMan/zookeeper#430]
Often, we'll targeting a CD add for files that have only been released physical for vinyl/cassette/digital-only

Track add will throw error:

```No Discogs tracks for Equanimity with media type CD found.```

This requires hand-importing of track names, and also doesn't catch the album art import from Discogs.

There's a workaround (import as vinyl, then edit to make it CD), but it would be cool if this could somehow be supported in a different way; it seems to me that trying to match the appropriate media type, but falling back to the first-available media type, would work fine (it's quite rare for different releases to have different track listings)

**Comment by RocketMan** [comment]
@bufordsharkley Do you have other examples besides Kems Kriol/Equanimity that I can use to test the change before I commit?

**Comment by bufordsharkley** [comment]
Not offhand (it's happened to me on many occasions so far, but I haven't been compiling the albums), but I can try to compile a dataset if that's useful

**Comment by RocketMan** [comment]
Changes have been deployed to enhance sophistication of the Discogs album match.

Previously, the Library Editor performed an exact format match.  Now, it will fallback to alternate formats, in the following order:
1. requested format (not including Promo or Limited/Special Edition)
2. requested format (any)
3. master
4. CD or vinyl that is not a Promo or Limited/Special edition
5. other (cassette, digital, promo, special edition, etc.)

I've tested it with as many cases as I could find and all looks good, but it might need finessing.  Let me know if you run into anything untoward.
