### ISSUE TITLE
Regression: A-File Activity

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#44]
Comparing 2.2.1 (prod) to 2.3.0-DEV (stage), the 'No playlist' entry on the A-File Activity page is missing. Is this intentional?

This entry is so the PD can quickly identify DJs who have not entered playlists. I am not sure this is so much a thing anymore, but it's worth checking with @bufordsharkley and the PD team.

**Comment by eric-gilbertson** [comment]
Will restore the 'no playlist' row.

**Comment by RocketMan** [comment]
Patch landed, closing
