### ISSUE TITLE
Logout link should close current OAuth session

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#45]
Currently clicking logout logs the user out of ZK but the existing OAuth session remains open thus requiring the user to click a second link to completely close the login state. Often the user neglects to do this and thus causing the next user to be logged in as someone else.

Suggested Change:
Clicking logout should close both the ZK login session and the Google/OAuth login and direct the user to the ZK login page.

**Comment by RocketMan** [comment]
Patch landed, closing.
