### ISSUE TITLE
Make the recent reviews view sortable & tweak the its UI

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#46]
Add client side sorting to the Recent Reviews view using the same table sorter used in the A file view and make the following additional changes:

   * show A file ID
   * Reivewed by -> Reviewer
   * show all A file albums in the list

**Comment by eric-gilbertson** [comment]
done.

**Comment by RocketMan** [comment]
Hello Eric, if you have these changes ready, please open a PR and I'll merge.

**Comment by RocketMan** [comment]
patch landed, closing
