### ISSUE TITLE
Edit a-file from main a-file page

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#5]
As the maintainer of the a-file, when I go back to edit something thats on the current a-file (e.g., pull date, genre chart), to get into the edit mode, I have to find the specific week the album was added in. Thats kind of a pain.  I want to be able to edit the a-file directly from the main a-file page.

**Comment by RinTinCan** [comment]
merged to master, kzsu on 2018-06-07

**Comment by RocketMan** [comment]
Patch landed.  Closing.
