### ISSUE TITLE
Add ability to log psa's, promo's etc in zookeeper

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#50]
Currently non-music related broadcast events such as PSA's and promo's (henceforth referred to as NMEs (non-music entries) must be logged using a cumbersome Google forms interface requiring DJs to maintain two distinct web pages during a show.  The on air process would be easier if these events were instead logged using the existing ZK track entry page.  Upon submission an NME is logged in the tracks table in a manner similar to music entries thereby eliminating the need for DB changes. 

NME entry is accessed via the addition of  NME type entries to the entry type drop-down in the playlist entry page (after the standard Manual Entry and Tag Entry music options). Upon selection of an NME option, an entry box is displayed into which the NME name or ID is entered, eg. 0022. Upon submit a timestamped entry is added to the tracks table with the NME entry type and ID recorded in the track and album columns respectively. The process for musical entries would not be impacted. By assigning the artist name for these entries to the SPECIAL_TRACK value they entries are not displayed in the playlists.
       
OPEN ISSUES:
   * should NMEs be displayed in playlists (perhaps yes when view internally and no otherwise)
   * what (if any) new reports are required to meet FCC log requirements
   * which Google docs events need to be implemented in ZK, eg psa, promo, login/logout/
   * should the NME types be hardcoded or defined in a PHP config file
   * if login/logout events are supported does that require return of the published show control

**Comment by RocketMan** [comment]
Thanks Eric!

Patch landed, closing.
