### ISSUE TITLE
Unexpected line break in playlist Time column

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#51]
Browser:  Firefox 60.8.0 esr
Zookeeper: 2.3.0 (prod)
Playlist:  https://zookeeper.stanford.edu/?action=viewDate&seq=selList&playlist=39176&session=

FYI, I am seeing an unexpected line break in the Time column for the above referenced playlist link (see attached).  For me, this affects only Firefox; the timestamp column is fine in epiphany/WebKit 2.24.3.

I should also add that this is the first and only playlist I have ever seen display like this, even in Firefox.

Expected:  The space between the numeric time and AM/PM should be non-breaking.

![Screenshot from 2019-07-17 12-52-01](https://user-images.githubusercontent.com/6860356/61373638-3f2b3a80-a892-11e9-8320-539b3026c1ba.png)

**Comment by eric-gilbertson** [comment]
the wrapp/ing is due to the non-standard entry at 5:09 which causes FF to squash the columns due to the long album and title strings that contain no spaces.  suggest fix: do nothing or add a spaces around the '/' character in the album/label column (thereby providing a line wrap opportunity this type of entry..

**Comment by RocketMan** [comment]
Thanks Eric.  Breaking around the / character is a good idea; perhaps add <wbr> or something like that following the slash, to give the browser a hint it is a line break point.  That way, it will break there if needed, but otherwise, there is no extra space.  TBD:  Is <wbr> supported in all the major browsers?

As for the space between the time and AM/PM, how about &nbsp; so that we're guaranteed it will not break no matter what?

**Comment by eric-gilbertson** [comment]
fixed by adding surrounding the album & label slash with spaces. forgot to implement the other suggestions but this is enough to resolve the issue.
