### ISSUE TITLE
Simplify new playlist form entry

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#57]
Simplify new playlist form. Currently the process for creating a new playlist is cumbersome, requiring the user to pick show start & end times from a long pick lists. Suggest the following changes in order to simplify this process:

    * use html time element for entering show start time
    * initialize start time to the current time rounded to the quarter hour
    * replace show end time control with a duration control (in hours)
    * store DJ's previous show configuration in local storage and default input values to it
    * use layout & styling used in the new track editor view

**Comment by RocketMan** [comment]
Thanks Eric.  These usability improvements complement the playlist editor changes nicely.  Can we fold this into the forthcoming release, so the playlist editor changes go out together?

**Comment by eric-gilbertson** [comment]
hey jim, i can probably get to this feature this weekend. if you don't mind waiting then that would be fine with me.

**Comment by RocketMan** [comment]
Hello Eric, that's perfect.

**Comment by RocketMan** [comment]
Patch landed, closing
