### ISSUE TITLE
Fix artist name swapping for special cases, eg CSN&Y and apply to Ajax requests

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#58]
Fix artist name swapping for special cases, eg CSN&Y. The name swapper reverses the &lt;LAST&gt;, &lt;FRIST&gt; name order in the ZK DB to &lt;FIRST&gt;  &lt;LAST&gt; for improved readability. The problem is that the implementation munges the order for certain names. Challenge is to not apply swapping in those special cases while preserving it for the majority of names. Name swapping should also be applied to the output of Ajax requests that generate artist names, eg the onnow request.

Suggest Fix:
Do not apply name wapping if the base string contains special characters, eg '&'.

**Comment by RocketMan** [comment]
Good idea!  I like that we're refining this.

In addition to the special character test, one possible additional test to prevent unintended swapping could be this:  If a single word (no spaces) follows 'and' or the final comma, then do not apply name swapping.  This would prevent swapping in cases like Romain's, 'The Choir of St. John's College, Cambridge' (one word following the comma), as well as things like, 'Peter, Paul and Mary' (one word following 'and').  Counter example:  'Peter, Paul and John Smith'  Here, there is more than one word following 'and', so normal swapping would apply => Paul Peter and John Smith.

**Comment by eric-gilbertson** [comment]
I've simplified the logic do only swap names if there is a single comma and the name is not manually entered. This covers all of the above issues. Can you think of any other test cases?

**Comment by RocketMan** [comment]
Sounds good to me.  It is one of those things that we can continue to finesse going forward if and as needed.

**Comment by RocketMan** [comment]
Patch landed 2.4.1; closing
