### ISSUE TITLE
Apply artist name swapping to REST query results & add limit parameter

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#65]
Apply artist name swapping to REST query results. Currently the getPlaylistsRq request returns artist names as <LAST>, <FIRST>. Since the output of this command is used to show what's playing it would be better if the playlist name swapper were applied to this output. Also suggest adding an optional 'limit' parameter so that the requester can specify how many items it needs.

**Comment by RocketMan** [comment]
Patch landed (sans 'limit' parameter), closing.
