### ISSUE TITLE
Perform artist name swapping on <LAST>, <FIRST><KEY_PHRASE> names

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#90]
Currently name swapping is not performed on names like "Bunnett, Jane And Maqueque" because the earlier more liberal swap algorithm mangled some names. The current rule could be extended by performing swapping when the first name is followed by key phrases such as " and " or ", Feat. " thereby safely providing improved readability for these common name formats. Examples include tags 1137967 (Bunnett, Jane And Maqueque) and 1139824 (Valera, Kiki, Feat. Coco Freeman)

**Comment by RocketMan** [comment]
Hello Eric, was this included in the most recent PRs?  Please let me know so I can tag the milestone.

**Comment by eric-gilbertson** [comment]
hi james, yes this was included in that PR.
