### ISSUE TITLE
Home page cleanup

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#92]
The home page layout is hard to decipher and the code is overly complex. Fix with:

   * normalize layout, eg use same on now format that is used in the playlist pages
   * perform artist name swap in top 10 of home page
   * restore artist name swap in playlist views
   * remove redundant displays of station name in home page
   * reduce use of tables for simple layout using html/css instead
   * left justify home page  te
   * add station_dir config parameter to identify station specific subdirs, eg img/kzsu
   * add kzsu favicon.ico
   * move swapNames to UICommon
   * replace " with ' when possible
   * remove NN4 browser check

**Comment by RocketMan** [comment]
patch landed and deployed to stage, closing
