### ISSUE TITLE
NME entries are displayed in view playlist

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#99]
NME entries are  displayed in view playlist. Reproduce by viewing the playlist for 'hanging in the bone yard' on  12/7. In it the PROMO/PSA & LIDs are visible. Suggest supressing all special track entries when viewing a playlist.

**Comment by RocketMan** [comment]
I cannot reproduce this.  The log entries are visible only if I am logged in; otherwise, they show as set separators.
![Screenshot from 2019-12-09 09-58-59](https://user-images.githubusercontent.com/6860356/70426287-abd5ea00-1a6a-11ea-85cb-9bf63f1998b1.png)

**Comment by eric-gilbertson** [comment]
Closing. I can no longer reproduce this.
